# Vistazo general de los datasets

In [1]:
import pandas as pd

## 1. 'results.csv'

In [2]:
df_results = pd.read_csv("../data/raw/results.csv")

In [3]:
df_results.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

## 2. 'fifa_ranking-2026-04-01.csv'

In [4]:
df_ranking = pd.read_csv("../data/raw/fifa_ranking-2026-04-01.csv")

In [5]:
df_ranking.head()

,Unnamed: 0,rank,country_full,country_abrv,total_points,previous_points,rank_change,confederation,rank_date
0,0,140.0,Brunei Darussalam,BRU,2.0,0.0,140,AFC,1992-12-31
1,1,33.0,Portugal,POR,38.0,0.0,33,UEFA,1992-12-31
2,2,32.0,Zambia,ZAM,38.0,0.0,32,CAF,1992-12-31
3,3,31.0,Greece,GRE,38.0,0.0,31,UEFA,1992-12-31
4,4,30.0,Algeria,ALG,39.0,0.0,30,CAF,1992-12-31

## 3. 'former_names.csv'

In [6]:
df_names = pd.read_csv("../data/raw/former_names.csv")

In [8]:
df_names.head()

          current                former  start_date    end_date
0           Benin               Dahomey  1959-11-08  1975-11-30
1    Burkina Faso           Upper Volta  1960-04-14  1984-08-04
2         Curaçao  Netherlands Antilles  1957-03-03  2010-10-10
3  Czechoslovakia               Bohemia  1903-04-05  1919-01-01
4  Czechoslovakia   Bohemia and Moravia  1939-01-01  1945-05-01

## 4. 'shootouts.csv'

In [9]:
df_shootouts = pd.read_csv("../data/raw/shootouts.csv")

In [10]:
df_shootouts.head()

         date    home_team         away_team       winner first_shooter
0  1967-08-22        India            Taiwan       Taiwan           NaN
1  1971-11-14  South Korea  Vietnam Republic  South Korea           NaN
2  1972-05-07  South Korea              Iraq         Iraq           NaN
3  1972-05-17     Thailand       South Korea  South Korea           NaN
4  1972-05-19     Thailand          Cambodia     Thailand           NaN